title: TAE30 IoT Lab Materials
description: Internet of Things Laboratory Materials for UC Davis
baseurl: "/TAE30-IoT-Lab-Materials"
url: "https://mohammadrezanarimaniucdavis.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore

# Include files
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap